# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-12 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0002_pattern_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='writing',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
