# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-26 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0003_pattern_url'),
        ('pattern', '0004_auto_20170112_1105'),
    ]

    operations = [
    ]
