# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-13 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0005_merge_20170226_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identity',
            name='ident',
        ),
    ]
