# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-13 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0006_remove_identity_ident'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='ident',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
