# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0008_auto_20170424_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pattern',
            old_name='url',
            new_name='audiourl',
        ),
        migrations.AlterField(
            model_name='pattern',
            name='status',
            field=models.CharField(choices=[(b'error', b'Error'), (b'editing', b'Editing'), (b'pending', b'Pending'), (b'rendering', b'Rendering'), (b'live', b'Live')], max_length=10),
        ),
    ]
