# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0010_pattern_loves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pattern',
            name='loves',
        ),
        migrations.AddField(
            model_name='pattern',
            name='loves',
            field=models.ManyToManyField(related_name='pattern_loves', to='pattern.Identity'),
        ),
    ]
