# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0011_auto_20170425_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pattern.Pattern'),
        ),
    ]
