# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0012_pattern_child'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pattern',
            old_name='child',
            new_name='parent',
        ),
    ]
